spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://movie-service
          predicates:
            - Path=/foo
          filters:
#            - PrefixPath=/movie
            - AddResponseHeader=X-Response-Red, Blue
            - RewritePath=/foo, /movie

#https://www.baeldung.com/spring-cloud-gateway